### ISSUE TITLE
Scaled images can break Sharp resizing

### ISSUE THREAD

**Issue by ashleahhill** [TrigenSoftware/flexis-srcset#62]
I have an image that is 2593px wide and I want to scale it down by half.

I am using https://github.com/TrigenSoftware/flexis-srcset-loader. My config can be seen here: https://github.com/TrigenSoftware/flexis-srcset-loader/issues/16

```
Error: Expected positive integer for width but received 1296.5 of type number
    at Object.invalidParameterError (<project_path>/node_modules/@flexis/srcset/node_modules/sharp/lib/is.js:101:10)
    at Sharp.resize (<project_path>/node_modules/@flexis/srcset/node_modules/sharp/lib/resize.js:197:16)
    at SrcsetGenerator.processImage (<project_path>/node_modules/@flexis/srcset/lib/index.js:312:19)
    at <project_path>/node_modules/@flexis/srcset/lib/index.js:269:56
    at Generator.next (<anonymous>)
    at resume (<project_path>/node_modules/@flexis/srcset/node_modules/@babel/runtime/helpers/AsyncGenerator.js:27:28)
    at <project_path>/node_modules/@flexis/srcset/node_modules/@babel/runtime/helpers/AsyncGenerator.js:20:9
    at new Promise (<anonymous>)
    at AsyncGenerator.send [as _invoke] (<project_path>/node_modules/@flexis/srcset/node_modules/@babel/runtime/helpers/AsyncGenerator.js:7:12)
    at AsyncGenerator.next (<project_path>/node_modules/@flexis/srcset/node_modules/@babel/runtime/helpers/AsyncGenerator.js:89:15)
    at Promise.all.rules.map (<project_path>/node_modules/@flexis/srcset-loader/lib/index.js:204:95)
```

I think the issue is `calculatedWidth`:

```
const calculatedWidth = originWidth && width <= 1 ? width * originWidth : width;
```

The `true` value should be rounded before assigning.

**Comment by dangreen** [comment]
@ashleahhill thank you for pr, fix was published.
